name: Deployment
on:
  push:
    branches:
      - main
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: npm ci
      - run: npm test
      - run: npm run build  
      - run: npm install -g serve
      - run: serve -s build &
      - run: disown
      - run: echo "This job's status is ${{ job.status }}."
