name: Deployment
on:
  push:
    branches:
      - main
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: npm ci
      - run: npm test
      - run: npm run build  
      - run: mv -f -v build/* /var/www/82.165.59.182
      - run: echo "This job's status is ${{ job.status }}."
